### ISSUE TITLE
[sga.estatisticas] Erro no Relatório de Serviços Codificados

### ISSUE THREAD

**Issue by rogeriolino** [novosga/novosga#256]
```
[Semantical Error] line 0, col 42 near 'c) as total,
': Error: Invalid PathExpression. Must be a StateFieldPathExpression.

#0 /var/www/html/novosga/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(483): Doctrine\ORM\Query\QueryException::semanticalError('line 0, col 42 ...', Object(Doctrine\ORM\Query\QueryException))
#1 /var/www/html/novosga/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(800): Doctrine\ORM\Query\Parser->semanticalError('Invalid PathExp...', Array)
#2 /var/www/html/novosga/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(279): Doctrine\ORM\Query\Parser->processDeferredPathExpressions(Object(Doctrine\ORM\Query\AST\SelectStatement))
#3 /var/www/html/novosga/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(351): Doctrine\ORM\Query\Parser->getAST()
#4 /var/www/html/novosga/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(281): Doctrine\ORM\Query\Parser->parse()
#5 /var/www/html/novosga/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(293): Doctrine\ORM\Query->_parse()
#6 /var/www/html/novosga/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(969): Doctrine\ORM\Query->_doExecute()
#7 /var/www/html/novosga/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(924): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache(NULL, 1)
#8 /var/www/html/novosga/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(727): Doctrine\ORM\AbstractQuery->execute(NULL, 1)
#9 /var/www/html/novosga/modules/sga/estatisticas/EstatisticasController.php(385): Doctrine\ORM\AbstractQuery->getResult()
#10 /var/www/html/novosga/modules/sga/estatisticas/EstatisticasController.php(144): modules\sga\estatisticas\EstatisticasController->servicos_codificados('2015-08-01', '2015-08-24 23:5...', 0)
#11 [internal function]: modules\sga\estatisticas\EstatisticasController->relatorio(Object(Novosga\Context))
#12 /var/www/html/novosga/public/index.php(120): ReflectionMethod->invokeArgs(Object(modules\sga\estatisticas\EstatisticasController), Array)
#13 [internal function]: {closure}('sga.estatistica...', Array)
#14 /var/www/html/novosga/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#15 /var/www/html/novosga/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#16 /var/www/html/novosga/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#17 /var/www/html/novosga/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#18 /var/www/html/novosga/src/Novosga/Slim/InstallMiddleware.php(33): Slim\Middleware\MethodOverride->call()
#19 /var/www/html/novosga/src/Novosga/Slim/AuthMiddleware.php(72): Novosga\Slim\InstallMiddleware->call()
#20 /var/www/html/novosga/vendor/slim/slim/Slim/Slim.php(1302): Novosga\Slim\AuthMiddleware->call()
#21 /var/www/html/novosga/public/index.php(135): Slim\Slim->run()
#22 {main}
```

**Comment by rogeriolino** [comment]
Reportado em http://forum.novosga.org/discussion/449/erro-no-relatorio-de-servicos-codificados
