### ISSUE TITLE
Slim Application Error

### ISSUE THREAD

**Issue by lfelisiak** [novosga/novosga#295]
Hi, I got this strange error from the novosga panel, already tried deleting vendor src bin and public folders and copying them from a fresh installed instance with no success, can anyone provide me some help of what's exactly going on? 
```
Slim Application Error
The application could not run because of the following error:

Details

Type: ReflectionException
Message: The parameter class is expected to be either a string or an object
File: /var/www/clients/client2/web2/web/src/Novosga/Model/Util/UsuarioSessao.php
Line: 308
Trace

#0 /var/www/clients/client2/web2/web/src/Novosga/Model/Util/UsuarioSessao.php(308): ReflectionMethod->__construct(NULL, 'getSessionId')
#1 /var/www/clients/client2/web2/web/src/Novosga/Slim/AuthMiddleware.php(38): Novosga\Model\Util\UsuarioSessao->__call('getSessionId', Array)
#2 /var/www/clients/client2/web2/web/src/Novosga/Slim/AuthMiddleware.php(38): Novosga\Model\Util\UsuarioSessao->getSessionId()
#3 /var/www/clients/client2/web2/web/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Novosga\Slim\AuthMiddleware->call()
#4 /var/www/clients/client2/web2/web/vendor/slim/slim/Slim/Slim.php(1300): Slim\Middleware\PrettyExceptions->call()
#5 /var/www/clients/client2/web2/web/public/index.php(135): Slim\Slim->run()
#6 {main}
```

**Comment by lfelisiak** [comment]
Ehm... Could be a certain bug?... trying to trace the reason of the problem, y was debugging the whole function and nothing more at all , when I refreshed the page to see things with debug, the environment was up and running again.

**Comment by rogeriolino** [comment]
Hi @lfelisiak what is your PHP version?

**Comment by rogeriolino** [comment]
Newest version are using Symfony framework.

**Comment by lfelisiak** [comment]
PHP -v : 5.6

**Comment by lfelisiak** [comment]
So with Symfony there shouldn't be any troubles? , I will check that!

**Comment by rogeriolino** [comment]
@lfelisiak the project was refactored, this trouble was solved.
